package fr.acart.wendy.website.resource

object Strings {
    val copyRights = "© Wendy Henault | Comportementaliste félin - 2025 Tous droits réservés - CGV - Mentions Légales"
    val contactMe = "Me Contacter :"
    val followMe = "Me Suivre :"
    val navContactMe = "Me Contacter et prendre rendez-vous"
    val altPhone = "Téléphone"
    val wendyEmail = "wendycomportementaliste86@gmail.com"
    val wendyPhone = "06.98.78.18.03"
    val wendyInstagram = "@wendy_comportementaliste86"
    val altInstagram = "Instagram"
    val altLogo = "Logo du site : un chat"
    val altPatoune = "Patoune"
    val minou = "Minou"
    val navWhoAmI = "Qui suis-je ?"
    val navWhenToConsult = "Quand me consulter ?"
    val navServices = "Mes Prestations"
    val navTestimonials = "Témoignages"
    val altContactIcon = "Icône de contact"
    val altPaw = "Patounette"
    val altCuteCat = "Chat mignon"
    val titleWendy = "Wendy Henault - Comportementaliste félin"
    val hook1 = "Une communication"
    val hook2 = "sans griffes"
    val hook3 = "avec votre chat !"
    val discoverTestimonials = "Découvrir les témoignages"
    val testimonials = "Vos témoignages"
    val altCatLurking = "Chat qui guette"
    val altProfilePicture = "Photo de profil de Wendy Henault"
    val shortPresentation = "J’interviens dans l’ensemble du département de la Vienne (86) mais je suis également disponible en visioconférence."
}